#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

HOME_BREWFILE="${HOME}/Brewfile"
LOCAL_BREWFILE="${SCRIPT_DIR}/../public/homebrew/Brewfile"

brew_bundle_install() {
  if [ -f "${HOME_BREWFILE}" ]; then
    echo "Installing homebrew dependencies from ${HOME_BREWFILE}"
    brew bundle check --file "${HOME_BREWFILE}" 
  elif [ -f "${LOCAL_BREWFILE}" ]; then
    echo "Installing initial homebrew dependencies from ${LOCAL_BREWFILE}"
    brew bundle check --file "${LOCAL_BREWFILE}"
  fi
}

echo "Running ${SCRIPT_DIR}/bootstrap ..."

if ! command -v brew &> /dev/null
then
    echo "homebrew could not be found, please install. See: https://brew.sh/"
    exit 255
fi

brew_bundle_install

if [[ ! -e ${HOME}/.stow-global-ignore ]]; then
    touch ${HOME}/.stow-global-ignore
fi
