alias reload='. ~/.bashrc'
alias a='atom .'
alias shitter='cd ~/git/veralite/ && bin/lasttripped; cd - > /dev/null'
alias drun='docker run --rm -i -t'
alias rnl='rename-and-link'
alias gid='pbpaste | ruby -r base64 -e '"'"'puts Base64.decode64(STDIN.read)'"'"''
